name: RepoGuard-AI scan

on:
  push:
    branches: ["**"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scan:
    name: Run RepoGuard-AI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install openai PyYAML requests truffleHog; fi

      - name: Run RepoGuard scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optionally set LLM_ENDPOINT as a repo secret to use local LLMs
          # LLM_ENDPOINT: ${{ secrets.LLM_ENDPOINT }}
        run: |
          # Ensure the repository contains repoguard.py and repoguard.yml
          python repoguard.py --config repoguard.yml --base "${{ github.event.before }}"

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: repoguard-results
          path: repoguard_results.json
